top_srcdir   = /home/osnapdev/322/httpd-2.4.25
top_builddir = /home/osnapdev/322/httpd-2.4.25
srcdir       = /home/osnapdev/322/httpd-2.4.25/modules/loggers
builddir     = /home/osnapdev/322/httpd-2.4.25/modules/loggers
VPATH        = /home/osnapdev/322/httpd-2.4.25/modules/loggers

include $(top_srcdir)/build/special.mk

