top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev
srcdir       = /home/osnapdev/httpd-2.4.25/modules/echo
builddir     = /home/osnapdev/modules/echo
VPATH        = /home/osnapdev/httpd-2.4.25/modules/echo

include $(top_srcdir)/build/special.mk

