top_srcdir   = /home/osnapdev/322/httpd-2.4.25
top_builddir = /home/osnapdev/322/httpd-2.4.25
srcdir       = /home/osnapdev/322/httpd-2.4.25/server/mpm/event
builddir     = /home/osnapdev/322/httpd-2.4.25/server/mpm/event
VPATH        = /home/osnapdev/322/httpd-2.4.25/server/mpm/event
include $(top_srcdir)/build/special.mk
