top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev
srcdir       = /home/osnapdev/httpd-2.4.25/modules/filters
builddir     = /home/osnapdev/modules/filters
VPATH        = /home/osnapdev/httpd-2.4.25/modules/filters

include $(top_srcdir)/build/special.mk

