top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev
srcdir       = /home/osnapdev/httpd-2.4.25/os
builddir     = /home/osnapdev/os
VPATH        = /home/osnapdev/httpd-2.4.25/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
