top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev/httpd-2.4.25
srcdir       = /home/osnapdev/httpd-2.4.25/modules/generators
builddir     = /home/osnapdev/httpd-2.4.25/modules/generators
VPATH        = /home/osnapdev/httpd-2.4.25/modules/generators

include $(top_srcdir)/build/special.mk

