top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev
srcdir       = /home/osnapdev/httpd-2.4.25/modules/dav/main
builddir     = /home/osnapdev/modules/dav/main
VPATH        = /home/osnapdev/httpd-2.4.25/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
