top_srcdir   = /home/osnapdev/httpd-2.4.25
top_builddir = /home/osnapdev
srcdir       = /home/osnapdev/httpd-2.4.25/modules/core
builddir     = /home/osnapdev/modules/core
VPATH        = /home/osnapdev/httpd-2.4.25/modules/core

include $(top_srcdir)/build/special.mk

